name: "Re-Run failed Jobs"

on: [push]

jobs:
  upload_testflight:
    name: TestFlight upload
    runs-on: macos-14
    steps:
      - name: Upload app to TestFlight
        uses: sikandernoori/upload-testflight-build@master
        with:
          app-path: ./ipa-production-release/app.ipa
          issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
          api-key-id: ${{ secrets.APPSTORE_API_KEY_ID }}
          api-private-key: ${{ secrets.APPSTORE_API_PRIVATE_KEY }}
          retry-attempts-on-timeout: 2
