name: "Re-Run failed Jobs"

on: [push]

jobs:
  always_fail:
    name: Always Fail Job
    runs-on: ubuntu-latest
    env:
      MAX_RETRIES: 5
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Simulate Failure
        id: simulate_failure
        run: |
          echo "This step will always fail."
          exit 1
        continue-on-error: true

      - name: Check and Retry if Failed
        id: retry_job
        run: |
          echo "Job failed, retrying..."
          RETRY_COUNT=0
          SUCCESS=false
          until [[ $SUCCESS == true || $RETRY_COUNT -ge $MAX_RETRIES ]]; do
            ((RETRY_COUNT++))
            echo "Retrying ($RETRY_COUNT/$MAX_RETRIES)..."
            if bash -c 'echo "This step will always fail."; exit 1'; then
              SUCCESS=true
              echo "Job succeeded on retry $RETRY_COUNT"
            else
              echo "Retry $RETRY_COUNT failed."
            fi
            sleep 10 # Delay to avoid immediate retry
          done
          if [[ $SUCCESS == false ]]; then
            echo "Job failed after $MAX_RETRIES retries"
            exit 1
          fi

      - name: Handle Failure
        if: failure()
        run: |
          echo "Job failed after retries."
          exit 1
