name: "Re-Run failed Jobs"

on: [push]

jobs:
  always_fail:
    name: Always Fail Job
    runs-on: ubuntu-latest
    steps:
      - name: This step always fails
        run: exit 1

  retry-on-failure:
        if: failure() && fromJSON(github.run_attempt) < 3
        needs: [always_fail]
        runs-on: ubuntu-latest
        steps:
          - env:
              GH_REPO: ${{ github.repository }}
              GH_TOKEN: ${{ github.token }}
            run: gh workflow run retry-workflow.yml -F retry=3
