name: Retry workflow

on:
  workflow_dispatch:
    inputs:
      retry:
        type: number
        description: How many time retry

jobs:
    rerun:
        runs-on: ubuntu-latest
        permissions:
          actions: write
        steps:
            - name: rerun ${{ inputs.retry }}
              env:
                  GH_REPO: ${{ github.repository }}
                  GH_TOKEN: ${{ github.token }}
              run: |
                  gh run watch ${{ inputs.retry }} > /dev/null 2>&1
                  gh run rerun ${{ inputs.retry }} --failed